-- JYYR STORE - Supabase / PostgreSQL schema
-- Run this in Supabase SQL Editor.
-- Uses Supabase Auth for authentication and RLS for authorization.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  full_name text not null default '',
  role text not null default 'user' check (role in ('user','admin')),
  saldo numeric(14,2) not null default 0 check (saldo >= 0),
  point bigint not null default 0 check (point >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.levels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  min_point bigint not null default 0 check (min_point >= 0),
  reward numeric(14,2) not null default 0 check (reward >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  category text not null default 'Lainnya',
  price numeric(14,4) not null check (price > 0),
  min_quantity integer not null check (min_quantity > 0),
  max_quantity integer not null check (max_quantity >= min_quantity),
  icon text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep existing projects compatible when this schema is re-run.
alter table public.products add column if not exists sort_order integer not null default 0;

create table if not exists public.broadcasts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text not null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  target text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(14,4) not null check (unit_price >= 0),
  total numeric(14,2) not null check (total >= 0),
  payment_method text not null check (payment_method in ('dana','qris')),
  status text not null default 'pending' check (status in ('pending','processing','success','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique references public.orders(id) on delete cascade,
  method text not null check (method in ('dana','qris')),
  proof_path text,
  status text not null default 'pending' check (status in ('pending','verified','rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.point_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_id text references public.orders(id) on delete set null,
  delta bigint not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_broadcasts_created_at on public.broadcasts(created_at desc);
create index if not exists idx_point_ledger_user_id on public.point_ledger(user_id);

-- Automatically create a profile after Supabase Auth signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'username',''), split_part(new.email,'@',1)),
    coalesce(new.raw_user_meta_data->>'full_name','')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products for each row execute procedure public.set_updated_at();
drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders for each row execute procedure public.set_updated_at();

-- Admin check. Kept outside the exposed schema in spirit; public function is used by RLS.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.levels enable row level security;
alter table public.products enable row level security;
alter table public.broadcasts enable row level security;
alter table public.orders enable row level security;
alter table public.payments enable row level security;
alter table public.point_ledger enable row level security;

-- Profiles: users see/update themselves; admins can manage all.
drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles for select to authenticated
using ((select auth.uid()) = id or (select public.is_admin()));

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_admin_only on public.profiles for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Levels: everyone authenticated can read; admins manage.
drop policy if exists levels_select_auth on public.levels;
create policy levels_select_auth on public.levels for select to authenticated using (true);
drop policy if exists levels_admin_insert on public.levels;
create policy levels_admin_insert on public.levels for insert to authenticated with check ((select public.is_admin()));
drop policy if exists levels_admin_update on public.levels;
create policy levels_admin_update on public.levels for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists levels_admin_delete on public.levels;
create policy levels_admin_delete on public.levels for delete to authenticated using ((select public.is_admin()));

-- Products: users read active products; admins read/manage all.
drop policy if exists products_select on public.products;
create policy products_select on public.products for select to authenticated
using (active = true or (select public.is_admin()));
drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert on public.products for insert to authenticated with check ((select public.is_admin()));
drop policy if exists products_admin_update on public.products;
create policy products_admin_update on public.products for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete on public.products for delete to authenticated using ((select public.is_admin()));

-- Broadcasts: authenticated users read; only admins create/update/delete.
drop policy if exists broadcasts_select_auth on public.broadcasts;
create policy broadcasts_select_auth on public.broadcasts for select to authenticated using (true);
drop policy if exists broadcasts_admin_insert on public.broadcasts;
create policy broadcasts_admin_insert on public.broadcasts for insert to authenticated with check ((select public.is_admin()) and created_by = (select auth.uid()));
drop policy if exists broadcasts_admin_delete on public.broadcasts;
create policy broadcasts_admin_delete on public.broadcasts for delete to authenticated using ((select public.is_admin()));

-- Orders: users see/create their own; admins manage all.
drop policy if exists orders_select_own_or_admin on public.orders;
create policy orders_select_own_or_admin on public.orders for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_admin()));
drop policy if exists orders_insert_own on public.orders;
create policy orders_insert_own on public.orders for insert to authenticated
with check (user_id = (select auth.uid()));
drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update on public.orders for update to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

-- Payments: user sees own payment; admin manages.
drop policy if exists payments_select_own_or_admin on public.payments;
create policy payments_select_own_or_admin on public.payments for select to authenticated
using ((select public.is_admin()) or exists (select 1 from public.orders o where o.id = order_id and o.user_id = (select auth.uid())));
drop policy if exists payments_insert_own on public.payments;
create policy payments_insert_own on public.payments for insert to authenticated
with check (exists (select 1 from public.orders o where o.id = order_id and o.user_id = (select auth.uid())));
-- Payment status/reviewer fields must only be changed by admin_review_payment().
drop policy if exists payments_admin_update on public.payments;
-- Intentionally no UPDATE policy is granted to browser clients.
-- The SECURITY DEFINER review RPC performs the controlled state transition.

-- Point ledger: users see their own history; admins see/manage.
drop policy if exists points_select_own_or_admin on public.point_ledger;
create policy points_select_own_or_admin on public.point_ledger for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_admin()));
drop policy if exists points_admin_insert on public.point_ledger;
create policy points_admin_insert on public.point_ledger for insert to authenticated with check ((select public.is_admin()));

-- Seed defaults. Safe to run repeatedly.
insert into public.levels (name, min_point, reward) values
('Basic',0,0),('VIP',1000,10000),('VVIP',5000,50000)
on conflict (name) do update set min_point=excluded.min_point,reward=excluded.reward;

insert into public.products (name,category,price,max_quantity,min_quantity,icon,active,sort_order) values
('TikTok Followers 🇮🇩','TikTok',75,99999,50,'https://i.ibb.co.com/PZg1TdRR/FOLLOWERS-Jyy-R.png',true,0),
('TikTok Likes 🇮🇩','TikTok',39,99999,50,'https://i.ibb.co.com/d0qDjYGh/LIKE-S-Jyy-R.png',true,1),
('TikTok Views 🇮🇩','TikTok',2.2,99999,1000,'https://i.ibb.co.com/pjhQ07gT/VIEW-S-Jyy-R.png',true,2),
('TikTok Komen 🇮🇩','TikTok',300,99999,10,'https://i.ibb.co.com/67sjz4nf/KOMENTAR-Jyy-R.png',true,3),
('TikTok Shares 🇮🇩','TikTok',1.7,99999,1000,'https://i.ibb.co.com/twDVyVD3/SHARE-S-Jyy-R.png',true,4),
('TikTok Saves 🇮🇩','TikTok',2.7,99999,1000,'https://i.ibb.co.com/Cs6QyT48/SAVE-S-Jyy-R.png',true,5),
('Instagram Followers 🇮🇩','Instagram',60,99999,50,'https://i.ibb.co.com/PZg1TdRR/FOLLOWERS-Jyy-R.png',true,0),
('Instagram Likes 🇮🇩','Instagram',30,99999,100,'https://i.ibb.co.com/d0qDjYGh/LIKE-S-Jyy-R.png',true,1),
('Instagram Views 🇮🇩','Instagram',0.75,99999,1000,'https://i.ibb.co.com/pjhQ07gT/VIEW-S-Jyy-R.png',true,2),
('Instagram Shares 🇮🇩','Instagram',1.1,99999,1000,'https://i.ibb.co.com/twDVyVD3/SHARE-S-Jyy-R.png',true,3),
('Instagram Saves 🇮🇩','Instagram',7.5,99999,100,'https://i.ibb.co.com/Cs6QyT48/SAVE-S-Jyy-R.png',true,4)
on conflict (name) do update set
  category=excluded.category,
  price=excluded.price,
  max_quantity=excluded.max_quantity,
  min_quantity=excluded.min_quantity,
  icon=excluded.icon,
  active=excluded.active;

-- Important: create the admin Auth user from Supabase Dashboard/Auth, then run:
-- update public.profiles set role='admin' where username='admin';
-- Never put a service_role key in index.html or any browser file.


-- 2) Make payment review atomic and idempotent.
create or replace function public.admin_review_payment(
  p_payment_id uuid,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment public.payments%rowtype;
  v_order public.orders%rowtype;
  v_point_gain bigint := 0;
  v_new_point bigint;
  v_already_awarded boolean := false;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  if p_status not in ('verified','rejected') then
    raise exception 'Invalid payment status';
  end if;

  select * into v_payment
  from public.payments
  where id = p_payment_id
  for update;

  if not found then
    raise exception 'Payment not found';
  end if;

  if v_payment.status <> 'pending' then
    raise exception 'Payment sudah direview sebelumnya';
  end if;

  select * into v_order
  from public.orders
  where id = v_payment.order_id
  for update;

  if not found then
    raise exception 'Order not found';
  end if;

  if p_status = 'rejected' then
    update public.payments
      set status = 'rejected',
          reviewed_by = auth.uid(),
          reviewed_at = now()
    where id = v_payment.id;

    update public.orders
      set status = 'cancelled',
          updated_at = now()
    where id = v_order.id;

    return jsonb_build_object(
      'payment_id', v_payment.id,
      'order_id', v_order.id,
      'payment_status', 'rejected',
      'order_status', 'cancelled',
      'point_gain', 0
    );
  end if;

  update public.payments
    set status = 'verified',
        reviewed_by = auth.uid(),
        reviewed_at = now()
  where id = v_payment.id;

  -- Point = floor(total / 1000), exactly once per order.
  v_point_gain := floor(v_order.total / 1000);

  select exists (
    select 1
    from public.point_ledger
    where order_id = v_order.id
      and delta > 0
      and reason = 'Payment verified reward'
  ) into v_already_awarded;

  if v_point_gain > 0 and not v_already_awarded then
    update public.profiles
      set point = point + v_point_gain,
          updated_at = now()
    where id = v_order.user_id
    returning point into v_new_point;

    insert into public.point_ledger(user_id, order_id, delta, reason)
    values (v_order.user_id, v_order.id, v_point_gain, 'Payment verified reward');
  else
    select point into v_new_point from public.profiles where id = v_order.user_id;
  end if;

  update public.orders
    set status = case when status = 'cancelled' then 'cancelled' else 'processing' end,
        updated_at = now()
  where id = v_order.id;

  return jsonb_build_object(
    'payment_id', v_payment.id,
    'order_id', v_order.id,
    'payment_status', 'verified',
    'order_status', case when v_order.status = 'cancelled' then 'cancelled' else 'processing' end,
    'point_gain', case when v_already_awarded then 0 else v_point_gain end,
    'new_point', v_new_point
  );
end;
$$;

revoke all on function public.admin_review_payment(uuid,text) from public;
grant execute on function public.admin_review_payment(uuid,text) to authenticated;

-- 3) Prevent an order from becoming processing/success before payment verification.
create or replace function public.guard_order_payment_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status in ('processing','success') then
    if not exists (
      select 1 from public.payments p
      where p.order_id = new.id
        and p.status = 'verified'
    ) then
      raise exception 'Payment must be verified before order can be processing/success';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists guard_order_payment_status on public.orders;
create trigger guard_order_payment_status
before update of status on public.orders
for each row execute procedure public.guard_order_payment_status();


-- ==========================================================
-- AUDIT LEDGER: MANUAL SALDO / POINT
-- ==========================================================
create table if not exists public.balance_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  delta numeric(14,2) not null,
  balance_after numeric(14,2) not null check (balance_after >= 0),
  reason text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_balance_ledger_user_id on public.balance_ledger(user_id, created_at desc);
