-- JYYR STORE — ADMIN SETUP
-- Create the admin user in Supabase Dashboard → Authentication → Users.
-- Use the real email you want for the admin account.
-- Then set that profile's role to admin with:
--
-- update public.profiles
-- set role='admin', full_name='JYYR Admin'
-- where username='ajiriansyah324';
--
-- Or use the user's actual UUID instead of username.
-- Never put a service_role key in browser code.
