-- JYYR Store Media V4.9.4
-- Final LIVE sync: point expiry, RPC privilege hardening, and frontend error logs.
-- Idempotent. Run after 102_owner_bootstrap_v4_9_4.sql.

-- =========================================================
-- 1) FRONTEND ERROR LOGGING
-- =========================================================
CREATE TABLE IF NOT EXISTS public.error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  type text not null default 'frontend',
  message text not null default '',
  stack text not null default '',
  created_at timestamptz not null default now()
);
ALTER TABLE public.error_logs ADD COLUMN IF NOT EXISTS type text;
ALTER TABLE public.error_logs ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE public.error_logs ADD COLUMN IF NOT EXISTS stack text;
UPDATE public.error_logs
SET type=COALESCE(type,'frontend'),
    message=COALESCE(message,''),
    stack=COALESCE(stack,'')
WHERE type IS NULL OR message IS NULL OR stack IS NULL;
ALTER TABLE public.error_logs ALTER COLUMN type SET DEFAULT 'frontend';
ALTER TABLE public.error_logs ALTER COLUMN message SET DEFAULT '';
ALTER TABLE public.error_logs ALTER COLUMN stack SET DEFAULT '';
ALTER TABLE public.error_logs ALTER COLUMN type SET NOT NULL;
ALTER TABLE public.error_logs ALTER COLUMN message SET NOT NULL;
ALTER TABLE public.error_logs ALTER COLUMN stack SET NOT NULL;
ALTER TABLE public.error_logs DROP COLUMN IF EXISTS error_message;
ALTER TABLE public.error_logs DROP COLUMN IF EXISTS error_stack;
ALTER TABLE public.error_logs DROP COLUMN IF EXISTS context;
CREATE INDEX IF NOT EXISTS idx_error_logs_created ON public.error_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_error_logs_user_created ON public.error_logs(user_id,created_at DESC);
ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.error_logs FROM PUBLIC, anon;
GRANT SELECT, INSERT ON TABLE public.error_logs TO authenticated;
DROP POLICY IF EXISTS error_logs_select_admin ON public.error_logs;
DROP POLICY IF EXISTS error_logs_admin_select ON public.error_logs;
DROP POLICY IF EXISTS error_logs_insert_own ON public.error_logs;
CREATE POLICY error_logs_admin_select ON public.error_logs
  FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY error_logs_insert_own ON public.error_logs
  FOR INSERT TO authenticated
  WITH CHECK (user_id=(select auth.uid()) OR user_id IS NULL);

-- =========================================================
-- 2) POINT EXPIRY
-- =========================================================
CREATE OR REPLACE FUNCTION public.expire_points_for_user()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public
AS $$
DECLARE
  v bigint:=0;
  r record;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  FOR r IN
    SELECT l.id,l.delta
    FROM public.point_ledger l
    WHERE l.user_id=auth.uid()
      AND l.delta>0
      AND l.expires_at IS NOT NULL
      AND l.expires_at<=now()
      AND NOT EXISTS (
        SELECT 1 FROM public.point_ledger x
        WHERE x.reason='Expiration of point ledger #'||l.id
      )
  LOOP
    INSERT INTO public.point_ledger(user_id,delta,reason)
    VALUES(auth.uid(),-r.delta,'Expiration of point ledger #'||r.id);
    v:=v+r.delta;
  END LOOP;

  IF v>0 THEN
    UPDATE public.profiles
    SET point=greatest(0,point-v),updated_at=now()
    WHERE id=auth.uid();
  END IF;

  RETURN v;
END;
$$;
REVOKE ALL ON FUNCTION public.expire_points_for_user() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.expire_points_for_user() TO authenticated;

-- =========================================================
-- 3) ADMIN RPC EXECUTE PRIVILEGES
--    Internal is_admin_writer()/Owner guards remain unchanged.
-- =========================================================
REVOKE EXECUTE ON FUNCTION public.admin_adjust_balance(uuid,numeric,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_adjust_point(uuid,bigint,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_bulk_order_status(text[],text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_delete_user(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_refund_order(text,numeric,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_review_deposit(uuid,text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_review_payment(uuid,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_admin_level(uuid,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_status(uuid,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_store_settings(numeric,numeric,numeric,numeric,numeric,boolean,boolean,boolean,text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_user_profile(uuid,text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_verify_user(uuid,boolean) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.admin_adjust_balance(uuid,numeric,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_adjust_point(uuid,bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_bulk_order_status(text[],text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_refund_order(text,numeric,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_review_deposit(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_review_payment(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_admin_level(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_status(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_store_settings(numeric,numeric,numeric,numeric,numeric,boolean,boolean,boolean,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_user_profile(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_verify_user(uuid,boolean) TO authenticated;
