-- JYYR STORE V4.5 — FINAL INTEGRITY PATCH
-- Run AFTER all other V4.5 migrations.

begin;

-- =========================================================
-- 1) GUARANTEE PROFILE CREATION AFTER SUPABASE AUTH SIGNUP
-- =========================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_username text;
  v_name text;
begin
  v_username := lower(trim(coalesce(new.raw_user_meta_data->>'username','')));
  v_name := trim(coalesce(new.raw_user_meta_data->>'full_name',''));

  if v_username = '' then
    v_username := lower(split_part(coalesce(new.email,''),'@',1));
  end if;

  insert into public.profiles(
    id, username, full_name, role, saldo, point,
    account_status, verified, admin_level, created_at, updated_at
  )
  values(
    new.id, v_username, v_name, 'user', 0, 0,
    'active', false, 'readonly', now(), now()
  )
  on conflict (id) do update set
    full_name=case when public.profiles.full_name='' then excluded.full_name else public.profiles.full_name end,
    username=case when public.profiles.username='' then excluded.username else public.profiles.username end,
    updated_at=now();

  return new;
exception when unique_violation then
  raise exception 'Username sudah digunakan';
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- 2) FRONTEND ERROR LOGGING
-- =========================================================
create table if not exists public.error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  type text not null,
  message text not null,
  stack text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists idx_error_logs_created on public.error_logs(created_at desc);
create index if not exists idx_error_logs_user_created on public.error_logs(user_id,created_at desc);
alter table public.error_logs enable row level security;
drop policy if exists error_logs_admin_select on public.error_logs;
create policy error_logs_admin_select on public.error_logs for select to authenticated using(public.is_admin());
drop policy if exists error_logs_insert_own on public.error_logs;
create policy error_logs_insert_own on public.error_logs for insert to authenticated with check(user_id=(select auth.uid()) or user_id is null);

-- =========================================================
-- 3) SAFE ORDER ROLLBACK AFTER POST-ORDER PAYMENT FAILURE
-- =========================================================
create or replace function public.cancel_pending_order(p_order_id text)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare o public.orders%rowtype;
begin
  select * into o from public.orders where id=trim(p_order_id) for update;
  if not found then return false; end if;
  if o.user_id<>(select auth.uid()) and not public.is_admin_writer() then
    raise exception 'Order bukan milik user saat ini';
  end if;
  if o.status<>'pending' then return false; end if;

  update public.orders
  set status='cancelled', cancel_reason='Checkout/payment creation gagal sebelum pembayaran dibuat.', updated_at=now()
  where id=o.id and status='pending';

  insert into public.order_events(order_id,status,note,created_by)
  values(o.id,'cancelled','Order dibatalkan otomatis karena tahap pembayaran gagal.',auth.uid());
  return found;
end;
$$;
revoke all on function public.cancel_pending_order(text) from public;
grant execute on function public.cancel_pending_order(text) to authenticated;

-- =========================================================
-- 4) PRIVATE PAYMENT-PROOF STORAGE
-- =========================================================
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('payment-proofs','payment-proofs',false,2097152,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false,file_size_limit=2097152,allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists payment_proofs_select_own_or_admin on storage.objects;
create policy payment_proofs_select_own_or_admin on storage.objects for select to authenticated
using(bucket_id='payment-proofs' and ((storage.foldername(name))[1]=(select auth.uid())::text or public.is_admin()));

drop policy if exists payment_proofs_insert_own on storage.objects;
create policy payment_proofs_insert_own on storage.objects for insert to authenticated
with check(bucket_id='payment-proofs' and (storage.foldername(name))[1]=(select auth.uid())::text);

drop policy if exists payment_proofs_update_own_or_admin on storage.objects;
create policy payment_proofs_update_own_or_admin on storage.objects for update to authenticated
using(bucket_id='payment-proofs' and ((storage.foldername(name))[1]=(select auth.uid())::text or public.is_admin()))
with check(bucket_id='payment-proofs' and ((storage.foldername(name))[1]=(select auth.uid())::text or public.is_admin()));

drop policy if exists payment_proofs_delete_own_or_admin on storage.objects;
create policy payment_proofs_delete_own_or_admin on storage.objects for delete to authenticated
using(bucket_id='payment-proofs' and ((storage.foldername(name))[1]=(select auth.uid())::text or public.is_admin()));

commit;
