-- JYYR STORE V4 — SAFE SPLIT MIGRATION
-- Generated against the live JYYR core schema discovered during this session.
-- Run using database/README.md. Stop on the first error.
-- No external API is required.

BEGIN;

-- =========================================================
-- CORE PROFILE / PRODUCT / ORDER EXTENSIONS
-- =========================================================
alter table public.profiles
  add column if not exists account_status text not null default 'active'
    check (account_status in ('active','suspended','banned')),
  add column if not exists verified boolean not null default false,
  add column if not exists admin_level text not null default 'admin'
    check (admin_level in ('super_admin','admin','readonly')),
  add column if not exists last_login_at timestamptz;

alter table public.levels
  add column if not exists discount_percent numeric(5,2) not null default 0
    check (discount_percent between 0 and 100),
  add column if not exists point_bonus bigint not null default 0
    check (point_bonus >= 0);

alter table public.products
  add column if not exists description text not null default '',
  add column if not exists terms text not null default '',
  add column if not exists notes text not null default '',
  add column if not exists product_status text not null default 'published'
    check (product_status in ('draft','published')),
  add column if not exists scheduled_at timestamptz,
  add column if not exists scheduled_until timestamptz;

alter table public.orders
  drop constraint if exists orders_payment_method_check;
alter table public.orders
  add constraint orders_payment_method_check
  check (payment_method in ('dana','qris','balance'));

alter table public.orders
  drop constraint if exists orders_status_check;
alter table public.orders
  add constraint orders_status_check
  check (status in ('pending','processing','success','cancelled','failed'));

alter table public.orders
  add column if not exists admin_note text not null default '',
  add column if not exists customer_note text not null default '',
  add column if not exists cancel_reason text,
  add column if not exists reject_reason text;

alter table public.payments
  drop constraint if exists payments_method_check;
alter table public.payments
  add constraint payments_method_check
  check (method in ('dana','qris','balance'));

-- =========================================================
-- SETTINGS / CATEGORIES
-- =========================================================
create table if not exists public.store_settings (
  id boolean primary key default true check (id),
  min_deposit numeric(14,2) not null default 10000 check (min_deposit >= 0),
  max_deposit numeric(14,2) not null default 10000000 check (max_deposit >= min_deposit),
  max_balance numeric(14,2) not null default 50000000 check (max_balance >= 0),
  deposit_bonus_percent numeric(5,2) not null default 0 check (deposit_bonus_percent between 0 and 100),
  deposit_bonus_fixed numeric(14,2) not null default 0 check (deposit_bonus_fixed >= 0),
  store_open boolean not null default true,
  maintenance_mode boolean not null default false,
  kill_switch boolean not null default false,
  maintenance_message text not null default 'JYYR STORE sedang maintenance.',
  system_announcement text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.store_settings(id) values(true) on conflict (id) do nothing;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.categories(name,sort_order) values
('TikTok',0),('Instagram',1),('Lainnya',2)
on conflict (name) do nothing;

-- JYYR V4 prerequisite: balance ledger was present in the original base schema,
-- but it is missing from the live database. Create it idempotently here.
create table if not exists public.balance_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  delta numeric(14,2) not null,
  balance_after numeric(14,2) not null check (balance_after >= 0),
  reason text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_balance_ledger_user_id on public.balance_ledger(user_id, created_at desc);

-- =========================================================
-- WALLET
-- =========================================================
create table if not exists public.wallet_deposits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  bonus numeric(14,2) not null default 0 check (bonus >= 0),
  method text not null check (method in ('dana','qris')),
  proof_path text,
  status text not null default 'pending' check (status in ('pending','verified','rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  reject_reason text,
  created_at timestamptz not null default now()
);
create index if not exists idx_wallet_deposits_status_created on public.wallet_deposits(status,created_at desc);
create index if not exists idx_wallet_deposits_user_created on public.wallet_deposits(user_id,created_at desc);

create table if not exists public.refunds (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique references public.orders(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  reason text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- =========================================================
-- NOTIFICATIONS / SUPPORT / AUDIT / ACTIVITY
-- =========================================================
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'system',
  read_at timestamptz,
  scheduled_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_notifications_user_created on public.notifications(user_id,created_at desc);
create index if not exists idx_notifications_unread on public.notifications(user_id,read_at);

create table if not exists public.user_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  note text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  status text,
  note text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_order_events_order_created on public.order_events(order_id,created_at desc);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text not null default '',
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_admin_audit_created on public.admin_audit_logs(created_at desc);

create table if not exists public.login_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  event text not null,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists idx_login_activity_user_created on public.login_activity(user_id,created_at desc);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_id text references public.orders(id) on delete set null,
  subject text not null,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  status text not null default 'open' check (status in ('open','pending','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  message text not null,
  internal boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.faq_items (
  id bigint generated by default as identity primary key,
  question text not null unique,
  answer text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.help_articles (
  id bigint generated by default as identity primary key,
  title text not null unique,
  content text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.level_rewards_awarded (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  level_id bigint not null references public.levels(id) on delete cascade,
  reward numeric(14,2) not null,
  created_at timestamptz not null default now(),
  unique(user_id,level_id)
);

create table if not exists public.point_milestones (
  id bigint generated by default as identity primary key,
  threshold bigint not null unique check (threshold > 0),
  bonus_point bigint not null default 0 check (bonus_point >= 0),
  bonus_balance numeric(14,2) not null default 0 check (bonus_balance >= 0),
  active boolean not null default true
);

alter table public.point_ledger add column if not exists expires_at timestamptz;

create table if not exists public.point_expiry_settings (
  id boolean primary key default true check(id),
  enabled boolean not null default false,
  days integer not null default 365 check(days > 0)
);
insert into public.point_expiry_settings(id) values(true) on conflict(id) do nothing;

COMMIT;
